### ISSUE TITLE
i dont konw why the bounds parameter it doesn‘t work in persalys14.0(salome)

### ISSUE THREAD

**Issue by YuDe95** [persalys/persalys#7] opened 2024-06-22 02:41 UTC
define
def _exec(X0,X1):
    """Main function: *must* be present"""
    Y0 = X0*X1
    return Y0
![image](https://github.com/persalys/persalys/assets/47850236/f85d1062-da3b-4f6c-b049-affae54055e4)
![image](https://github.com/persalys/persalys/assets/47850236/c174d198-1674-4fed-b327-b59692e55dc7)
![image](https://github.com/persalys/persalys/assets/47850236/b799e225-5868-4301-ac19-09cced231f63)
![image](https://github.com/persalys/persalys/assets/47850236/d104db70-cba9-4ac8-b687-9fced0762f53)
![image](https://github.com/persalys/persalys/assets/47850236/0c4ccf09-0667-4606-8b0d-cd2c90bd1b24)
![image](https://github.com/persalys/persalys/assets/47850236/9a1e5e63-7522-4497-975b-e4e4e11351cc)
we can get the result x0,x1but the value it not in [4.5,5.5]

thanks!!!!!!

**Comment by jschueller** [comment] 2024-06-22 08:28
this is already fixed in version 16 (the problem is not feasible),and it will be available in a later salome release
thanks for the detailled bug report

**Closed as completed by jschueller** 2024-06-22 08:28 UTC

**Comment by YuDe95** [comment] 2024-08-16 05:24
Do you know how I can modify this issue in version 14.0，or  refer to whitch commit

**Comment by jschueller** [comment] 2024-08-16 06:35
i dont remember, maybe it was fixed in openturns

**Comment by YuDe95** [comment] 2024-08-16 06:51
thanks
